# Generated by Django 5.0.4 on 2025-03-22 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_item_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="created_by",
        ),
    ]
